#!/bin/bash
# ==============================================================================
# Hermes-Mythos: Enterprise-Grade Provisioning & Pairing Script
# Version: 2.2
# Targets: Docker, Multi-Provider LLM Gateway, Telegram, & WhatsApp
# ==============================================================================

set -e # Terminate on any error

# --- UI Definitions ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m' 

clear
echo -e "${CYAN}${BOLD}"
echo "======================================================================"
echo "    HERMES-MYTHOS: PRODUCTION ORCHESTRATOR DEPLOYMENT"
echo "======================================================================"
echo -e "${NC}"

# --- 1. Dependency & Environment Audit ---
install_dependencies() {
    echo -e "${YELLOW}[1/6] Auditing System Dependencies...${NC}"
    
    # Identify Sudo Requirement
    SUDO=''
    if [ "$(id -u)" != "0" ]; then 
        SUDO='sudo'
        echo -e "Note: Non-root user detected. Using sudo for system tasks."
    fi

    # Update Package Lists
    $SUDO apt-get update -qq

    # Required Packages
    DEPENDENCIES=(docker.io docker-compose git curl jq python3-pip)
    
    for dep in "${DEPENDENCIES[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            echo -e "Installing missing package: ${BOLD}$dep${NC}..."
            $SUDO apt-get install -y "$dep" > /dev/null 2>&1 || {
                echo -e "${RED}FAILURE: Could not install $dep. Ensure your apt sources are valid.${NC}"
                exit 1
            }
        fi
    done
    echo -e "${GREEN}Dependencies verified.${NC}"
}

# --- 2. Repository & Volume Initialization ---
setup_repo() {
    echo -e "${YELLOW}[2/6] Initializing Data Structures...${NC}"
    
    # Detect context
    if [ ! -d ".git" ]; then
        echo "Cloning latest improved architecture..."
        git clone https://github.com/chelotithehost-sketch/hermes-mythos-improved.git . || true
    fi

    # Create Persistent Volumes with appropriate permissions
    $SUDO mkdir -p manuscripts library_db mnt/data webhooks
    $SUDO chmod -R 777 manuscripts library_db mnt/data
}

# --- 3. Unified LLM Gateway Configuration ---
configure_llm() {
    echo -e "\n${CYAN}--- LLM GATEWAY CONFIGURATION ---${NC}"
    echo "Leave blank to skip a provider. At least one is required for 'The Brain'."
    
    read -p "Anthropic API Key: " ANTHROPIC_KEY
    read -p "OpenAI API Key: " OPENAI_KEY
    read -p "Gemini API Key: " GEMINI_KEY
    read -p "Mistral API Key: " MISTRAL_KEY
    read -p "Grok/xAI API Key: " GROK_KEY
}

# --- 4. Omnichannel Pairing (Guided) ---
configure_messaging() {
    echo -e "\n${CYAN}--- BOT PAIRING & OMNICHANNEL SETUP ---${NC}"
    
    # Telegram Pairing Logic
    echo -e "${BOLD}Telegram:${NC} Contact @BotFather, create a bot, and paste the API Token."
    read -p "Telegram Bot Token: " TELEGRAM_TOKEN

    # WhatsApp Pairing Logic (Meta Graph API)
    echo -e "\n${BOLD}WhatsApp:${NC} Configure your App at developers.facebook.com."
    read -p "WhatsApp Permanent Access Token: " WHATSAPP_TOKEN
    read -p "WhatsApp Business Phone ID: " WHATSAPP_ID
    read -p "Webhook Verify Token (Default: hermes_mythos_v2): " VERIFY_TOKEN
    VERIFY_TOKEN=${VERIFY_TOKEN:-hermes_mythos_v2}

    # Fetch Public IP for Webhook Registration
    PUBLIC_IP=$(curl -s ifconfig.me)

    # Write the Immutable .env
    {
        echo "# GENERATED BY HERMES PROVISIONER"
        echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY"
        echo "OPENAI_API_KEY=$OPENAI_KEY"
        echo "GEMINI_API_KEY=$GEMINI_KEY"
        echo "MISTRAL_API_KEY=$MISTRAL_KEY"
        echo "GROK_API_KEY=$GROK_KEY"
        echo ""
        echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_TOKEN"
        echo "WHATSAPP_ACCESS_TOKEN=$WHATSAPP_TOKEN"
        echo "WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_ID"
        echo "WHATSAPP_VERIFY_TOKEN=$VERIFY_TOKEN"
        echo ""
        echo "SERVER_URL=http://$PUBLIC_IP:8000"
        echo "OLLAMA_HOST=http://host.docker.internal:11434"
        echo "DB_PATH=/app/library_db/library.db"
        echo "LOG_LEVEL=INFO"
        echo "PYTHONMALLOC=malloc"
    } > .env
    echo -e "${GREEN}Environment configuration persistent.${NC}"
}

# --- 5. Containerized Deployment ---
deploy() {
    echo -e "\n${YELLOW}[5/6] Launching Containers (2GB RAM Hard-Limit)...${NC}"
    $SUDO docker-compose down > /dev/null 2>&1 || true
    $SUDO docker-compose up --build -d
}

# --- 6. Automated Webhook Registration (The "Handshake") ---
finalize_pairing() {
    echo -e "\n${YELLOW}[6/6] Finalizing Bot Handshake...${NC}"
    
    if [ ! -z "$TELEGRAM_TOKEN" ]; then
        echo -e "Registering Telegram Webhook..."
        RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/setWebhook" \
             -d "url=http://$PUBLIC_IP:8000/webhooks/telegram")
        if [[ $RESPONSE == *"\"ok\":true"* ]]; then
            echo -e "${GREEN}✓ Telegram Paired Successfully.${NC}"
        else
            echo -e "${RED}✗ Telegram Pairing Failed: $RESPONSE${NC}"
        fi
    fi

    echo -e "\n${CYAN}================== PAIRING SUMMARY ====================${NC}"
    echo -e "Server IP: ${BOLD}$PUBLIC_IP${NC}"
    echo -e "Orchestrator Port: ${BOLD}8000${NC}"
    echo -e "\n${BOLD}WhatsApp Manual Step:${NC}"
    echo -e "Paste this URL in Meta Dashboard: ${YELLOW}http://$PUBLIC_IP:8000/webhooks/whatsapp${NC}"
    echo -e "Use Verify Token: ${YELLOW}$VERIFY_TOKEN${NC}"
    echo -e "${CYAN}=======================================================${NC}"
}

# --- Execution Flow ---
install_dependencies
setup_repo
configure_llm
configure_messaging
deploy
finalize_pairing

echo -e "\n${GREEN}${BOLD}Hermes-Mythos is fully deployed and paired.${NC}"
echo -e "The 7-Layer Cognitive DAG is standing by."
